baseURL = "https://sooyoungro.github.io/"
metaDataFormat = "yaml"
title = "Sooyoungro Church"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
    languageName = "English(영어)"
  [languages.en.params]
    introTitle = "To The Father’s"
    introSubtitle = "New Year Special Morning Prayer"
    introPhoto = "/banner_en.png"
  [[languages.en.menu.main]]
    name = "Select"
    url = "blog"
    weight = 1

  [languages.kr]
    contentDir = "content/kr"
    weight = 1
    languageName = "한국어(Korean)"
  [languages.kr.params]
    introTitle = "아버지 집으로"
    introSubtitle = "연말연시특별새벽기도회"
    introPhoto = "/banner_kr.png"
  [[languages.kr.menu.main]]
    name = "Select"
    url = "blog"
    weight = 1

  [languages.cn]
    contentDir = "content/cn"
    weight = 1
    languageName = "汉语(Chinese)"
  [languages.cn.params]
    introTitle = "回父亲的家"
    introSubtitle = "跨年特别晨更祷告会"
    introPhoto = "/banner_cn.png"
  [[languages.cn.menu.main]]
    name = "Select"
    url = "blog"
    weight = 1

  [languages.jp]
    contentDir = "content/jp"
    weight = 1
    languageName = "日本語(Japan)"
  [languages.jp.params]
    introTitle = "父の家へ"
    introSubtitle = "年末年始特別早天祈祷会"
    introPhoto = "/banner_jp.png"
  [[languages.jp.menu.main]]
    name = "Select"
    url = "blog"
    weight = 1

  [languages.mm]
     contentDir = "content/mm"
     weight = 3
     languageName = "ဗမာ(Myanmar)"
 [languages.mm.params]
     introTitle = "အဖအိမ်သို့"
     introSubtitle = "နှစ်ကုန်၊ နှစ်သစ် အာရုဏ်ဦး အထူးဆုတောင်းအစီအစဥ်"
     introPhoto = "/cell.png"
  [[languages.mm.menu.main]]
     name = "Select"
     url = "blog"
     weight = 1

  # [languages.vi]
  #   contentDir = "content/vi"
  #   weight = 3
  #   languageName = "Tiếng Việt(Vietnamese)"
  # [languages.vi.params]
  #   introTitle = "Tiếng Việt(Vietnamese)"
  #   introSubtitle = "베트남어 영상 모음입니다."
  #   introPhoto = "/flag_china.png"
  # [[languages.vi.menu.main]]
  #   name = "Blog"
  #   url = "blog"
  #   weight = 1

  # [languages.ne]
  #   contentDir = "content/vi"
  #   weight = 3
  #   languageName = "नेपाली(Nepali)"
  # [languages.ne.params]
  #   introTitle = "नेपाली(Nepali)"
  #   introSubtitle = "네팔어 영상 모음입니다."
  #   introPhoto = "/flag_nepal.png"
  # [[languages.ne.menu.main]]
  #   name = "Blog"
  #   url = "blog"
  #   weight = 1

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2023 - Translation Team of Suhyungro Church International Missions Department · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-indigo-200"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = true

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = true

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = false

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = true

# [params.homepage.social]
#   # Global params common for both languages
#   title = "Follow me"
#   description = "I work on everything coding and tweet developer memes"

#   [[params.homepage.social.icons]]
#     website = "youtube"
#     url = "https://www.youtube.com/@sooyoungrochurch7718"

[[menu.main]]
  name = "Blogs"
  url = "/blog"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
